use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :graphql_sample, GraphqlSample.Endpoint,
  http: [port: "${PORT}"],
  url: [host: "${HOST}", port: "${PORT}"],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: "MsXaDjUl4pGhfKMNqw4Akw6iUdxL4t1bXUuWaF0dfNB9+pQ1O7CK2GQWCVQ0Bm/O",
  server: true,
  root: "."


# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :graphql_sample, GraphqlSample.Repo,
  adapter: Ecto.Adapters.Postgres,
  hostname: "${DB_HOSTNAME}",
  username: "${DB_USERNAME}",
  password: "${DB_PASSWORD}",
  database: "${DB_NAME}",
  pool_size: 20


  #username: System.get_env("DB_USER"),
  #password: System.get_env("DB_PASSWORD"),
  #hostname: "${DB_HOSTNAME}",
  #database: "graphql_sample_prod",
  #pool_size: 20
